version: '3.8'

services:
  database: 
    container_name: POSTGRES_DB_
    image: postgres:15
    restart: always
    ports: 
      - "5435:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-SkillSwap:/var/lib/postgresql/data

  backend:
    container_name: Backend
    build: ./backend/.
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    ports: 
      - "3000:3000"
    depends_on:
      - database

volumes:
  postgres-SkillSwap: