FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json* ./ 
RUN npm install

COPY . .

# RUN npm install -g typescript
RUN npm run build

RUN npx prisma generate

EXPOSE 3000

CMD ["node", "dist/index.js"]
