apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: voidxv/skillswap-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PLATFORM
          value: "docker"
        - name: DATABASE_URL
          value: "postgresql://root:admin@postgres:5432/SkillSwap_test"
          
        envFrom:
         - secretRef:
             name: backend-secret
