name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: SkillSwap_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://root:admin@localhost:5432/SkillSwap_test
      NODE_ENV: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Generate Prisma Client
        working-directory: backend
        run: npx prisma generate --schema=prisma/schema.prisma

      - name: Apply migrations to test DB
        working-directory: backend
        run: npx prisma migrate deploy --schema=prisma/schema.prisma

      - name: Run tests
        working-directory: backend
        run: npm test

      - name: Build project
        working-directory: backend
        run: npm run build

      - name: Logging into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: backend
        run: |
          COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/skillswap-backend:$COMMIT_SHA .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/skillswap-backend:$COMMIT_SHA
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/skillswap-backend:$COMMIT_SHA ${{ secrets.DOCKERHUB_USERNAME }}/skillswap-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/skillswap-backend:latest

      - name: Build and push Migrations Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: migrations
        run: |
          COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/skillswap-migrations:$COMMIT_SHA .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/skillswap-migrations:$COMMIT_SHA
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/skillswap-migrations:$COMMIT_SHA ${{ secrets.DOCKERHUB_USERNAME }}/skillswap-migrations:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/skillswap-migrations:latest
       